version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: imdb-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: imdb_reviews
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - imdb-network

  api:
    build: .
    container_name: imdb-api
    restart: always
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/imdb_reviews?authSource=admin
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./data:/app/data
    networks:
      - imdb-network

volumes:
  mongodb_data:

networks:
  imdb-network:
    driver: bridge
